
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itea_lesson
    password: postgres
    username: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/itea_lesson
    password: postgres
    user: postgres
server:
  port: 8081